name: Kernel module CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: [self-hosted, kernel-machine]

    steps:
    - uses: actions/checkout@v3
    - name: make
      run: make
      
